FROM python:3.9-slim

WORKDIR /app

COPY dependencies/requirements_0.txt .
RUN pip install --no-cache-dir -r requirements_0.txt

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/app

CMD ["python"]